### PR TITLE
Merge https://github.com/jwiegley/git-scripts/pull/42

### PR DESCRIPTION
**Pull request by danimesq**

### CODE REVIEW

**Comment by DaniellMesquita** [comment]
@bill-auger

**Comment by bill-auger** [comment]
hello - @jwiegley is the one whom needs a ping, in this case - do you happen to know if jwiegley plans to continue  maintaining the 'git-scripts' repo?

**Comment by jwiegley** [comment]
I don't actively maintain it anymore, so I'd be happy to hand it off to someone who wishes to do so.

**Comment by bill-auger** [comment]
On Thu, 27 Jan 2022 21:07:39 -0800 John wrote:
> I don't actively maintain it anymore, so I'd be happy to hand it off to someone who wishes to do so.

has that been suggested/discussed before? - if not, maybe open a
ticket on the jwiegley/git-scripts issue tracker, asking for
community opinions - >50 are "watching" - probably, many people
would answer positively, that someone should maintain the
collection

if it is important to people, but no one volunteers to do it, i
may be persuaded - i do not have much or (any time) for it though
- hopefully multiple people will, if enough are aware that he
collection need a new maintainer

**Pull request merged**
